// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicHeader: typeof import('./src/components/layouts/BasicHeader.vue')['default']
    BasicSide: typeof import('./src/components/layouts/BasicSide.vue')['default']
    ComposableFunction: typeof import('./src/views/composable-function/index.vue')['default']
    Counter: typeof import('./src/views/composable-function/counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    FunctionalComponent: typeof import('./src/views/guide/functional-component/index.vue')['default']
    Guide: typeof import('./src/views/guide/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Localstorage: typeof import('./src/views/composable-function/localstorage.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    Mouse: typeof import('./src/views/composable-function/mouse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Icons/src/test.vue')['default']
    TestElementPlus: typeof import('./src/views/TestElementPlus.vue')['default']
    Toggle: typeof import('./src/views/composable-function/toggle.vue')['default']
    TreeComponent: typeof import('./src/views/guide/tree-component/index.vue')['default']
  }
}
