// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		BasicHeader: typeof import('./../components/layouts/BasicHeader.vue')['default']
		BasicSide: typeof import('./../components/layouts/BasicSide.vue')['default']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
		ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElTag: typeof import('element-plus/es')['ElTag']
		HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
		Home: typeof import('./../views/Home.vue')['default']
		Login: typeof import('./../views/login/index.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		TestElementPlus: typeof import('./../views/TestElementPlus.vue')['default']
	}
}
