// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicHeader: typeof import('./../components/layouts/BasicHeader.vue')['default']
    BasicSide: typeof import('./../components/layouts/BasicSide.vue')['default']
    ComposableFunction: typeof import('./../views/composable-function/index.vue')['default']
    ComposeFunction: typeof import('./../views/compose-function/index.vue')['default']
    Counter: typeof import('./../views/composable-function/counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    FunctionalComponent: typeof import('./../views/guide/functional-component/index.vue')['default']
    Guide: typeof import('./../views/guide/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../views/Home.vue')['default']
    Localstorage: typeof import('./../views/composable-function/localstorage.vue')['default']
    Login: typeof import('./../views/login/index.vue')['default']
    Mouse: typeof import('./../views/composable-function/mouse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestElementPlus: typeof import('./../views/TestElementPlus.vue')['default']
    Toggle: typeof import('./../views/composable-function/toggle.vue')['default']
    TreeComponent: typeof import('./../views/guide/tree-component/index.vue')['default']
  }
}
